// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwzymwwbarojayqrgshz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3enltd3diYXJvamF5cXJnc2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTYzMzYsImV4cCI6MjA2MzczMjMzNn0.O5s8XxEyCivb8f4whZleTyvNNU84tZoxyCrDUpAUznc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);